### ISSUE TITLE
Compiling problems

### ISSUE THREAD

**Issue by HiperDoo** [JuanDiegoMontoya/Gengine#4] opened 2021-11-24 01:24 UTC
Hello and good morning, I loved the images you showed about your project and the capabilities it has, and I was interested in executing it, but unfortunately I got a list of errors in the console and then the window closed.

I am using Visual Studio 2019 (I didnt modify absolutely anything of the project), as I understood from the list of errors, my computer's characteristics may not be the minimum to run the program (CPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz 1.80 GHz   GPU: Intel(R) UHD Graphics 620   RAM: 8GB), or maybe I need to add some .dlls. But I'm very interested in running it; this is what I got on the console:

```
C:\b\w\bc4f22ce46571d95\sw\physx\PhysXSDK\4.1\trunk\source\cudamanager\src\CudaContextManager.cpp (632) : info : nvcuda.dll not found or could not be loaded.

C:\b\w\bc4f22ce46571d95\sw\physx\PhysXSDK\4.1\trunk\source\cudamanager\src\CudaContextManager.cpp (376) : info : NVIDIA Release 411 graphics driver and above is required for GPU acceleration.

File: TexturedMesh.fs.glsl
Error compiling shader of type 35632
ERROR: 0:10: 'location qualifer' : the "location" qualifier cannot be used when a "binding" qualifier is also provided. Use "offset" instead


File: chunk_optimized.fs.glsl
Error compiling shader of type 35632
ERROR: 0:6: 'location qualifer' : the "location" qualifier cannot be used when a "binding" qualifier is also provided. Use "offset" instead
ERROR: 0:8: 'location qualifer' : the "location" qualifier cannot be used when a "binding" qualifier is also provided. Use "offset" instead


File: compact_batch.cs.glsl
Error compiling shader of type 37305
WARNING: 0:3: '#extension' :  'GL_GOOGLE_include_directive' is not supported
ERROR: 0:3: '' : illegal character (") (0x22)
ERROR: 0:3: '' : illegal character (") (0x22)
ERROR: 0:4: '' : syntax error: #line
ERROR: 0:10: '' : illegal character (") (0x22)
ERROR: 0:10: '' : illegal character (") (0x22)
ERROR: 0:11: '' : syntax error: #line
ERROR: 0:32: '' : illegal character (") (0x22)
ERROR: 0:32: '' : illegal character (") (0x22)
ERROR: 0:33: '' : syntax error: #line


File: update_particle_emitter.cs.glsl
Error compiling shader of type 37305
WARNING: 0:3: '#extension' :  'GL_GOOGLE_include_directive' is not supported
ERROR: 0:3: '' : illegal character (") (0x22)
ERROR: 0:3: '' : illegal character (") (0x22)
ERROR: 0:4: '' : syntax error: #line
ERROR: 0:6: '' : illegal character (") (0x22)
ERROR: 0:6: '' : illegal character (") (0x22)
ERROR: 0:7: '' : syntax error: #line
ERROR: 0:52: '' : illegal character (") (0x22)
ERROR: 0:52: '' : illegal character (") (0x22)
ERROR: 0:53: '' : syntax error: #line
ERROR: 0:53: '' : illegal character (") (0x2
File: update_particle.cs.glsl
Error compiling shader of type 37305
WARNING: 0:3: '#extension' :  'GL_GOOGLE_include_directive' is not supported
ERROR: 0:3: '' : illegal character (") (0x22)
ERROR: 0:3: '' : illegal character (") (0x22)
ERROR: 0:4: '' : syntax error: #line
ERROR: 0:6: '' : illegal character (") (0x22)
ERROR: 0:6: '' : illegal character (") (0x22)
ERROR: 0:7: '' : syntax error: #line
ERROR: 0:52: '' : illegal character (") (0x22)
ERROR: 0:52: '' : illegal character (") (0x22)
ERROR: 0:53: '' : syntax error: #line
ERROR: 0:53: '' : illegal character (") (0x2
File: chunk_render_cull.vs.glsl
Error compiling shader of type 35633
WARNING: 0:3: '#extension' :  'GL_GOOGLE_include_directive' is not supported
ERROR: 0:3: '' : illegal character (") (0x22)
ERROR: 0:3: '' : illegal character (") (0x22)
ERROR: 0:4: '' : syntax error: #line
ERROR: 0:6: '' : illegal character (") (0x22)
ERROR: 0:6: '' : illegal character (") (0x22)
ERROR: 0:7: '' : syntax error: #line
ERROR: 0:28: '' : illegal character (") (0x22)
ERROR: 0:28: '' : illegal character (") (0x22)
ERROR: 0:29: '' : syntax error: #line


File: particle.vs.glsl
Error compiling shader of type 35633
WARNING: 0:3: '#extension' :  'GL_GOOGLE_include_directive' is not supported
ERROR: 0:3: '' : illegal character (") (0x22)
ERROR: 0:3: '' : illegal character (") (0x22)
ERROR: 0:4: '' : syntax error: #line
ERROR: 0:6: '' : illegal character (") (0x22)
ERROR: 0:6: '' : illegal character (") (0x22)
ERROR: 0:7: '' : syntax error: #line
ERROR: 0:52: '' : illegal character (") (0x22)
ERROR: 0:52: '' : illegal character (") (0x22)
ERROR: 0:53: '' : syntax error: #line


File: tonemap.fs.glsl
Error compiling shader of type 35632
ERROR: 0:3: 'location qualifer' : the "location" qualifier cannot be used when a "binding" qualifier is also provided. Use "offset" instead
ERROR: 0:4: 'location qualifer' : the "location" qualifier cannot be used when a "binding" qualifier is also provided. Use "offset" instead


File: fog.fs.glsl
Error compiling shader of type 35632
WARNING: 0:3: '#extension' :  'GL_GOOGLE_include_directive' is not supported
ERROR: 0:3: '' : illegal character (") (0x22)
ERROR: 0:3: '' : illegal character (") (0x22)
ERROR: 0:4: '' : syntax error: #line
ERROR: 0:5: '' : illegal character (") (0x22)
ERROR: 0:5: '' : illegal character (") (0x22)
ERROR: 0:6: '' : syntax error: #line
ERROR: 0:68: '' : illegal character (") (0x22)
ERROR: 0:68: '' : illegal character (") (0x22)
ERROR: 0:69: '' : syntax error: #line
ERROR: 0:74: 'location qualifer' : the "loca
File: fxaa.fs.glsl
Error compiling shader of type 35632
ERROR: 0:23: 'location qualifer' : the "location" qualifier cannot be used when a "binding" qualifier is also provided. Use "offset" instead


File: reflections/specular_cube_trace.fs.glsl
Error compiling shader of type 35632
WARNING: 0:3: '#extension' :  'GL_GOOGLE_include_directive' is not supported
ERROR: 0:3: '' : illegal character (") (0x22)
ERROR: 0:3: '' : illegal character (") (0x22)
ERROR: 0:4: '' : syntax error: #line
ERROR: 0:6: '' : illegal character (") (0x22)
ERROR: 0:6: '' : illegal character (") (0x22)
ERROR: 0:7: '' : syntax error: incorrect expression in preprocessor directive
ERROR: 0:7: '' : syntax error: #line
ERROR: 0:69: '' : illegal character (") (0x22)
ERROR: 0:69: '' : illegal character (") (0x22)
ERRO
File: reflections/unproject_depth.fs.glsl
Error compiling shader of type 35632
WARNING: 0:3: '#extension' :  'GL_GOOGLE_include_directive' is not supported
ERROR: 0:3: '' : illegal character (") (0x22)
ERROR: 0:3: '' : illegal character (") (0x22)
ERROR: 0:4: '' : syntax error: #line
ERROR: 0:6: '' : illegal character (") (0x22)
ERROR: 0:6: '' : illegal character (") (0x22)
ERROR: 0:7: '' : syntax error: incorrect expression in preprocessor directive
ERROR: 0:7: '' : syntax error: #line
ERROR: 0:69: '' : illegal character (") (0x22)
ERROR: 0:69: '' : illegal character (") (0x22)
ERRO
File: reflections/specular_composite.fs.glsl
Error compiling shader of type 35632
WARNING: 0:3: '#extension' :  'GL_GOOGLE_include_directive' is not supported
ERROR: 0:3: '' : illegal character (") (0x22)
ERROR: 0:3: '' : illegal character (") (0x22)
ERROR: 0:4: '' : syntax error: #line
ERROR: 0:6: '' : illegal character (") (0x22)
ERROR: 0:6: '' : illegal character (") (0x22)
ERROR: 0:7: '' : syntax error: incorrect expression in preprocessor directive
ERROR: 0:7: '' : syntax error: #line
ERROR: 0:69: '' : illegal character (") (0x22)
ERROR: 0:69: '' : illegal character (") (0x22)
ERRO
[17:11:25:582] [default] [critical] OpenGL Debug message (1282): Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error
Source: API
Type: Error
Severity: high
[17:11:25:585] [default] [critical] OpenGL Debug message (1282): Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error
Source: API
Type: Error
Severity: high
[17:11:25:589] [default] [critical] OpenGL Debug message (1282): Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error
Source: API
Type: Error
Severity: high
[17:11:25:591] [default] [critical] OpenGL Debug message (1282): Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error
Source: API
Type: Error
Severity: high
[17:11:25:593] [default] [critical] OpenGL Debug message (1282): Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error
Source: API
Type: Error
Severity: high
[17:11:25:595] [default] [critical] OpenGL Debug message (1282): Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error
Source: API
Type: Error
Severity: high
[17:11:25:596] [default] [critical] OpenGL Debug message (1282): Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error
Source: API
Type: Error
Severity: high
[17:11:25:597] [default] [critical] OpenGL Debug message (1282): Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error
Source: API
Type: Error
Severity: high
[17:11:25:608] [default] [warning] Texture air.png does not exist, using fallback.
[17:11:25:608] [default] [warning] Texture metal.png does not exist, using fallback.
[17:11:25:609] [default] [warning] Texture sand.png does not exist, using fallback.
[17:11:25:609] [default] [warning] Texture snow.png does not exist, using fallback.
[17:11:25:610] [default] [warning] Texture dry grass.png does not exist, using fallback.
[17:11:25:610] [default] [warning] Texture Olight.png does not exist, using fallback.
[17:11:25:611] [default] [warning] Texture Rlight.png does not exist, using fallback.
[17:11:25:611] [default] [warning] Texture Glight.png does not exist, using fallback.
[17:11:25:612] [default] [warning] Texture Blight.png does not exist, using fallback.
[17:11:25:612] [default] [warning] Texture Smlight.png does not exist, using fallback.
[17:11:25:613] [default] [warning] Texture Ylight.png does not exist, using fallback.
[17:11:25:872] [default] [info] Allocating chunks took 0.0088128 seconds
[17:11:25:954] [default] [info] Generating chunks took 0.0805243 seconds
[17:11:27:394] [default] [info] Sunlight propagation took 1.4396577 seconds
[17:11:27:555] [default] [info] Generating meshes took 0.1604142 seconds
[17:11:27:559] [default] [info] Buffering meshes took 0.0029115 seconds
Constructed particle emitter on entity 4
Constructed particle emitter on entity 5
[17:11:28:222] [default] [critical] OpenGL Debug message (1282): Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error
Source: API
Type: Error
Severity: high
[17:11:28:223] [default] [critical] OpenGL Debug message (1282): Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error
Source: API
Type: Error
Severity: high
[17:11:28:224] [default] [critical] OpenGL Debug message (1281): Error has been generated. GL error GL_INVALID_VALUE in (null): (ID: 173538523) Generic error
Source: API
Type: Error
Severity: high
[17:11:28:225] [default] [critical] OpenGL Debug message (1282): Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error
Source: API
Type: Error
Severity: high

C:\Users\davic\Desktop\Nueva carpeta\Gengine-master\Gengine-master\build\x64\Debug\VoxelEngine.exe (proceso 4240) se cerró con el código -1.
Para cerrar automáticamente la consola cuando se detiene la depuración, habilite Herramientas ->Opciones ->Depuración ->Cerrar la consola automáticamente al detenerse la depuración.
Presione cualquier tecla para cerrar esta ventana. . .
```

**Comment by JuanDiegoMontoya** [comment] 2021-11-24 10:05
Thank you for your interest and the detailed report! I see one of the issues is caused by a lack of support for **GL_GOOGLE_include_directive**. I know a workaround (two, actually), as that extension isn't very ubiquitous. One way is to simply remove all preprocessor directives regarding that extension (the includes are already processed by shaderc, so the only thing we'll miss is correct compiler errors on platforms that don't support this extension.

I didn't know this was an error, I guess Nvidia and AMD drivers are permissive here :sweat_smile:. This is a trivial fix.
 
    ERROR: 0:6: 'location qualifer' : the "location" qualifier cannot be used when a "binding" qualifier is also provided. Use "offset" instead

All the other errors are presumably caused by trying to bind an invalid shader program, which would be gone when I fix the above issues.

I can fix these issues soon, and when I do I'll close the issue.

**Comment by HiperDoo** [comment] 2021-11-24 16:04
Thank you! Then I could assume that when this thread is closed it will be resolved.

Good luck and thanks for answering!

**Comment by JuanDiegoMontoya** [comment] 2021-11-28 11:12
Hi @HiperDoo, try pulling and running the latest build from master. I made some changes that should fix the shader compilation issues on non-Nvidia hardware. However, I only tested on an AMD machine, so I won't know for sure that it worked until you (on an Intel iGPU) have tried.

**Comment by JuanDiegoMontoya** [comment] 2021-12-22 04:47
Closing as the issue has been resolved on the machines I've tested. Feel free to re-open or post a new issue if it persists.

**Closed as completed by JuanDiegoMontoya** 2021-12-22 04:47 UTC
